version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_ROOT_DATABASE: admin

    volumes:
      - ./scripts/mongo/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - docker-net

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4586:4566-4586"
      - "8055:8080"
    environment:
      - SERVICES=sqs                        # Especifique os serviços da AWS que deseja simular
      - DEFAULT_REGION=us-west-2            # Região padrão da AWS para simulação
      - AWS_REGION=us-west-2                # Região padrão da AWS para simulação
      - AWS_ACCESS_KEY_ID=notValidKey       # Credenciais de acesso simuladas
      - AWS_SECRET_ACCESS_KEY=notValidKey   # Chave secreta simulada
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack:/docker-entrypoint-initaws.d
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge